"use client";

import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "react-hot-toast";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { Provider } from "react-redux";
import store from "./store";

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <head>
          <link rel="icon" href="./icons.jpeg" type="image/jpeg" sizes="16x16" />
          <link rel="icon" href="./updatedicon.jpeg" type="image/jpeg"  />
          <link rel="icon" href="./icons.jpeg" type="image/jpeg" sizes="48x48" />
          <link rel="shortcut icon" href="/icons.jpeg" type="image/jpeg" />
          <link rel="apple-touch-icon" href="/icons.jpeg" sizes="180x180" />
          <link rel="apple-touch-icon" href="/icons.jpeg" sizes="152x152" />
          <link rel="apple-touch-icon" href="/icons.jpeg" sizes="120x120" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                fontSize: "14px",
              },
              success: {
                style: {
                  background: "#dcfce7",
                  color: "#166534",
                },
              },
              error: {
                style: {
                  background: "#fee2e2",
                  color: "#991b1b",
                },
              },
            }}
          />
          {children}
        </body>
      </html>
    </Provider>
  );
}
